# Train Configuration

# Train & Test Parameters
train:
  model_dir: model
  train_data: data/avazu/train.csv
  dev_data: data/avazu/dev.csv
  test_data:
  batch_size: 1000
  train_epochs: 20
  epochs_per_eval: 1
  steps_per_eval:
  keep_train: 0
  num_samples: 7300000
  checkpoint_path:
  skip_lines: 1
  field_delim: ','
  verbose: 0

# Model Parameters
model:
  hidden_units: [64, 64, 64]
  learning_rate: 0.1
  lr_decay: true
  lr_decay_steps: 1000
  lr_decay_rate: 0.95
  activation_function: tf.nn.relu
  l1: 0.01
  l2: 0.01
  dropout:
  batch_normalization: true

# Saving Parameters (Optional)
runconfig:
  tf_random_seed: 12345
  save_summary_steps: 10000
  save_checkpoints_steps: 100000
  save_checkpoints_secs:
  keep_checkpoint_max: 1
  keep_checkpoint_every_n_hours: 1
  log_step_count_steps: 1000

