# Train Configuration

# Train & Test Parameters
train:
  model_dir: mnn_model
  train_data: data/criteo/train.csv
  dev_data: data/criteo/dev.csv
  test_data:
  batch_size: 256
  train_epochs: 25
  epochs_per_eval: 1
  steps_per_eval:
  keep_train: 0
  num_samples: 5000000
  checkpoint_path:
  skip_lines:
  field_delim: '\t'
  verbose: 0

# Model Parameters
model:
  hidden_units: [64, 64, 64]
  learning_rate: 0.01
  lr_decay: true
  lr_decay_steps: 10000
  lr_decay_rate: 0.96
  activation_function: tf.nn.relu
  l1: 0.01
  l2: 0.01
  dropout:
  batch_normalization: true

# Saving Parameters (Optional)
runconfig:
  tf_random_seed:
  save_summary_steps: 1000
  save_checkpoints_steps: 100000
  save_checkpoints_secs:
  keep_checkpoint_max: 1
  keep_checkpoint_every_n_hours: 1
  log_step_count_steps: 1000









